import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Financify";
    in-out property <int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        LineEdit {
            placeholder-text: "Wage";
            height: 50px;
        }

        LineEdit {
            placeholder-text: "Length of Commute";
            height: 50px;
        }

        LineEdit {
            placeholder-text: "Fuel Efficiency";
            height: 50px;
        }

        Button {
            text: "CALCULATE";
            clicked => {
                root.request-increase-value();
            }
        }

        Button {
            text: "Real Wage";
            height: 50px;
            enabled: false;
        }
    }
}
