import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    height: 400px;
    width: 300px;
    title: @tr("Financify");
    icon: @image-url("financify.png");
    in-out property <string> real_wage: "$0.0/h over 0 hours";
    callback calc_real_wage(string, string, string, string);
    VerticalBox {
        wage := LineEdit {
            placeholder-text: "Wage";
            height: 50px;
        }

        commute := LineEdit {
            placeholder-text: "Length of Commute";
            height: 50px;
        }

        efficiency := LineEdit {
            placeholder-text: "Fuel Efficiency";
            height: 50px;
        }

        gas := LineEdit {
            placeholder-text: "Gas Price";
            height: 50px;
        }

        Button {
            text: "CALCULATE";
            clicked => {
                root.calc_real_wage(wage.text, commute.text, efficiency.text, gas.text);
            }
        }

        Button {
            text: root.real_wage;
            height: 50px;
            enabled: false;
        }
    }
}
